### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by tarner** [leandrokoiti/GoDaddyDnsUpdater#3]
I'm getting an error message.

Response status code does not indicate success 422 (Unprocessable Entity)

**Comment by sloov187** [comment]
I am getting the same error.

Response status code does not indicate success 422 (Unprocessable Entity)

**Comment by austonpramodh** [comment]
Same error here.....

**Comment by leandrokoiti** [comment]
Hey guys, have you guys entered your api key into the application?
Is there any chance that you are using a "test key" instead of a "production key" on GoDaddy? 
By reading this post on SO I believe it may be related to the key you are using:
https://stackoverflow.com/questions/39123202/error-422-when-using-powershell-to-update-dns-records-on-godaddy-api?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa
Can you test that?
Thanks!

**Comment by sloov187** [comment]
I was using a production key for sure.


________________________________

**Comment by mdwkelly** [comment]
Same issue here and was for sure using the production key.

Thanks

**Comment by leandrokoiti** [comment]
Hey guys so I finally had time to look into this issue, GoDaddy's API had a small change on the endpoint used to update the records, that's why the message, so I fixed and will commit the code and soon make a new release available for those who just want to download the application, thank you all and sorry for taking so long!
