### ISSUE TITLE
Record not updated

### ISSUE THREAD

**Issue by Saad-Alothman** [leandrokoiti/GoDaddyDnsUpdater#4]
Hello, thank you for this wonderful Tool!, i have downloaded it and splitted the code to use it in a console application , i will commit the code back if you like.

everything works with no errors, the only issue i am facing is that it is not updating the IP Address.
List of domains are returned, but the update is not happening and no error messages what so ever, i have been trying several times since yesterday and i am stuck. 

Any ideas ?

**Comment by leandrokoiti** [comment]
Hey Saad,
Sure, I can merge the code back into the main version!
About the update, I finally had a little bit of time to tweak the code and noticed that it will only update if the network card triggers an event, so I fixed that so it can be updated manually or on a fixed interval as well, I will try to merge my fix after your commit and maybe the other bugs that are being reported will be fixed as well since the problem you noticed was the last one that I was working on
Thanks for the help!

**Comment by leandrokoiti** [comment]
Hey Saad, finally found the problem: https://github.com/leandrokoiti/GoDaddyDnsUpdater/issues/3

**Comment by Saad-Alothman** [comment]
Great!!!

im gonna try it out and let you know what happens with me !
